### ISSUE TITLE
MainPage 기본 구조 마크업

### ISSUE THREAD

**Issue by Miaash** [hongseonga/Museum-website#1]
### Todo contents
- 메인 페이지 기본 구조 마크업 
- 상단, 중하단, 하단 나눠서 작업 진행

### Todo List
1. [x] top section 기본 구조 마크업
2. [x] middle section 기본 구조 마크업
3. [ ] bottom section 기본 구조 마크업

### Time
6h
